default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: MercuryDB
  username: Spikes
  password: 2212
  host: localhost
  port: 5432

test:
  <<: *default
production:
  <<: *default